#!/bin/bash

# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Check if all go files have been formatted
if [ $(gofmt -l . | wc -l | grep -q 0) ]; then
  tput setaf 1
  echo "You go files have not been formatted!"
  echo "Run 'make fmt' in project root directory to do so."
  tput setaf 7
  exit 1
fi
