#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# TODO: only check files staged for commit
# Check if all go files have been formatted
cd "${SCRIPT_DIR}"/../ || exit 1
PRE_COMMIT_RESULT="$(task check-linting)"
if [ $? != 0 ]; then
  tput setaf 1
  echo "Your go files have not been formatted properly!"
  echo "Run 'task fmt' in project root directory to do so."
  tput setaf 7
  echo ""
  echo "Linter output:"
  echo "$PRE_COMMIT_RESULT"
  exit 1
fi
